In [2]:
import numpy as np
import pandas as pd

In [3]:
data = {'color': ['white', 'red', 'blue'],
                  'items': ['ball', 'pen', 'pencil'],
                  'price': [2.5, 1.5, 0.5]}

frame = pd.DataFrame(data)
frame

,color,items,price
0,white,ball,2.5
1,red,pen,1.5
2,blue,pencil,0.5


In [4]:
frame2 = pd.DataFrame(data, columns=['items', 'price'])
frame2

,items,price
0,ball,2.5
1,pen,1.5
2,pencil,0.5


In [5]:
# Nested dict directly passed on to pd.DataFrame()
nesteddict = {'red': {2012:22, 2014:45},
'green': {2008:23, 2012:22, 2014:17},
'blue': {2008: 18, 2012:28, 2014:19}}

frame3 = pd.DataFrame(nesteddict)
frame3

,red,green,blue
2012,22.0,22,28
2014,45.0,17,19
2008,NaN,23,18


In [6]:
frame3.T

,2012,2014,2008
red,22.0,45.0,NaN
green,22.0,17.0,23.0
blue,28.0,19.0,18.0


In [6]:
import numpy as np
import pandas as pd
csvframe = pd.read_csv('M:/COMPSCI4084/WEEK3/Class4/texting1.txt', index_col=['color', 'status'])
csvframe

item1  item2  item3
color status                     
black up          3      4      6
      down        2      6      7
white up          5      5      5
      down        3      3      2
      left        1      2      1
red   up          2      2      2
      down        1      1      4

In [7]:
pd.read_table('M:/COMPSCI4084/WEEK3/Class4/texting2.txt', sep='\s+', engine='python')

,white,red,blue,green
0,1,5,2,3
1,2,7,8,5
2,3,3,6,7
3,2,2,8,3
4,4,4,2,1


In [8]:
# Databases 
from sqlalchemy import create_engine
frame = pd.DataFrame(np.arange(20).reshape(4,5),
                    columns=['white','red','blue','black','green'])
frame

,white,red,blue,black,green
0,0,1,2,3,4
1,5,6,7,8,9
2,10,11,12,13,14
3,15,16,17,18,19


In [10]:
engine = create_engine('sqlite:///foo.db')

In [11]:
frame.to_sql('colors',engine)

4

In [12]:
pd.read_sql('colors',engine)

,index,white,red,blue,black,green
0,0,0,1,2,3,4
1,1,5,6,7,8,9
2,2,10,11,12,13,14
3,3,15,16,17,18,19


In [ ]:
import sqlite3
import pandas as pd

df = pd.DataFrame()

conn = sqlite3.connect("students.db")

df.to_sql(
    "students", 
    conn, 
    if_exists="replace", 
    index=False
)

result = pd.read_sql(
    "SELECT * FROM students",
    conn
)

In [17]:
frame1 = pd.DataFrame({'id': ['ball', 'pencil', 'pen', 'mug', 'ashtray'],
                       'price': [12.33, 11.44, 33.21, 13.23, 33.62]})
frame1

,id,price
0,ball,12.33
1,pencil,11.44
2,pen,33.21
3,mug,13.23
4,ashtray,33.62


In [18]:
frame2 = pd.DataFrame({'id': ['pencil', 'pencil', 'ball', 'pen'],
                       'color': ['white', 'red', 'red', 'black']})
frame2

,id,color
0,pencil,white
1,pencil,red
2,ball,red
3,pen,black


In [19]:
pd.merge(frame1, frame2)

,id,price,color
0,ball,12.33,red
1,pencil,11.44,white
2,pencil,11.44,red
3,pen,33.21,black


In [21]:
# Concatenating
array1 = np.arange(9).reshape(3,3)
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
array2 = np.arange(9).reshape(3,3) + 6
array2

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [23]:
np.concatenate([array1, array2], axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11],
       [ 6,  7,  8, 12, 13, 14]])

In [24]:
np.concatenate([array1, array2], axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [26]:
# Series Concatenation
ser1 = pd.Series([0.326100, 0.983239, 0.306811, 0.149875], index=[1,2,3,4])
ser1

1    0.326100
2    0.983239
3    0.306811
4    0.149875
dtype: float64

In [27]:
ser2 = pd.Series(np.random.rand(4), index=[5,6,7,8])
ser2

5    0.937916
6    0.773916
7    0.765785
8    0.043132
dtype: float64

In [28]:
pd.concat([ser1, ser2])

1    0.326100
2    0.983239
3    0.306811
4    0.149875
5    0.937916
6    0.773916
7    0.765785
8    0.043132
dtype: float64

In [29]:
pd.concat([ser1, ser2], keys=[1, 2])

1  1    0.326100
   2    0.983239
   3    0.306811
   4    0.149875
2  5    0.937916
   6    0.773916
   7    0.765785
   8    0.043132
dtype: float64

In [30]:
pd.concat([ser1, ser2], axis=1, keys=[1,2])

,1,2
1,0.326100,NaN
2,0.983239,NaN
3,0.306811,NaN
4,0.149875,NaN
5,NaN,0.937916
6,NaN,0.773916
7,NaN,0.765785
8,NaN,0.043132
